<?php

/**
 * @file
 * Contains utilities.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function utilities_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the utilities module.
        case 'help.page.utilities':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('The utilities module for photo.kylehuynh.com') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function utilities_theme() {
    return [
        'utilities' => [
            'render element' => 'children',
        ],
        'photostream_block' => [
            'variables' => [
                'photos' => NULL
                
            ],
            'render element' => 'pager',
        ],
        
    ];
}
